stages:
  - publish
  - gendocs

router:
  image: node:lts
  stage: publish
  only:
    - master
  artifacts:
    paths:
      - badges/**
  script:
    - cd src/router
    - sh ../../deploy.sh
    - mkdir -p badges
    - export VERSION=$(node -e "console.log(require('./package.json').version)")
    - wget -O badges/version.svg https://img.shields.io/badge/version-${VERSION}-blue.svg
    - wget -O badges/size.svg https://img.shields.io/badge/size-6kb-green.svg
    - cp ../../readme.md .
    - cd ../../
    - cp -r src/router/badges .

animate:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/animate
    - sh ../../deploy.sh

transition:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/transition
    - sh ../../deploy.sh

preact:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/preact
    - sh ../../deploy.sh

react:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/react
    - sh ../../deploy.sh

svelte:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/svelte
    - sh ../../deploy.sh

vue:
  image: node:lts
  stage: publish
  only:
    - master
  script:
    - cd src/vue
    - sh ../../deploy.sh

gendocs:
  image: alshdavid/aws-cli
  stage: gendocs
  only:
    - master
  script:
    - sh <(curl -sSL https://alshdavid.github.io/alshx/bin/alshx) --install
    - aws s3 rm --recursive s3://alshdavid-public/crayon/badges
    - aws s3 cp --recursive ./badges s3://alshdavid-public/crayon/badges
    - aws cloudfront create-invalidation --distribution-id E2QHY39OWRUCEU --paths /\*
    - alshx hub-purge https://github.com/alshdavid/crayon